### ISSUE TITLE
Doubts about HTTP origin value in CloudFront

### ISSUE THREAD

**Issue by ShivamJoker** [MarkusWendorf/cdk-function-url#1]
I am not able to understand what the object is doing here, I couldn't find something related to this in the CDK docs

https://github.com/MarkusWendorf/cdk-function-url/blob/03969601da89879c1215eeb80dfb64e521ea2881/lib/infra-stack.ts#L31

It will be great if you could help me out here, Thanks!

**Comment by MarkusWendorf** [comment]
Hey @ShivamJoker 

this code is related to this issue: https://github.com/aws/aws-cdk/issues/20254

It basically takes the CDK output for the lambda function url `https://function-url.aws-lambda.whatever.com` and extracts the bare domain name which is required for the cloudfront origin. 

I should probably replace it now with `Fn.parseDomainName` which is a helper provided by the CDK team (which would do the same under the hood I assume).

**Comment by ShivamJoker** [comment]
Ohh okay thanks a lot.
